// src/app/layout.js
import React from 'react';
import dynamic from 'next/dynamic';
import { Layout, Menu } from 'antd';
import {
  UserOutlined,
  VideoCameraOutlined,
  UploadOutlined,
} from '@ant-design/icons';

// import globals.css
import './globals.css';
import './page.module.css';


// Dynamically import ClientLayout with SSR disabled
const ClientLayout = dynamic(() => import('./components/MainLayout/ClientLayout'), { ssr: false });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>


  );
}
